This notebook is for gathering basic information about the datasets FNDatasetGerman and GermanFakeNC, 
such as categories, unique URLs, how many articles of fake and legitimate news, etc.

In [2]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import numpy as np
import pandas as pd

from pprint import pprint

Analysis of the FNDatasetGerman dataset

In [3]:
FNDatasetGerman = pd.read_csv(r"datasets/FNDatasetGer.csv",encoding="utf-8")
FNDatasetGerman

,id,url,Titel,Body,Kategorie,Datum,Quelle,Fake,Art
0,773233,http://www.der-postillon.com/2018/01/grokoleak...,Exklusiv! Das geheime WhatsApp-Chat-Protokoll ...,Die Sondierungsgespräche zwischen Union und SP...,wirtschaft,2018-01-18 00:00:00,Postillion,1,NaN
1,773234,http://www.der-postillon.com/2018/01/trump-san...,"Trump droht, jeden zu verspeisen, der an seine...",Nun ist es auch medizinisch offiziell bestätig...,wirtschaft,2018-01-17 00:00:00,Postillion,1,NaN
2,773235,http://www.der-postillon.com/2018/01/fdp-sondi...,"Soli runter, keine Steuererhöhungen, kein Klim...","Es waren zähe Verhandlungen, doch die Freien D...",wirtschaft,2018-01-12 00:00:00,Postillion,1,NaN
3,773236,http://www.der-postillon.com/2018/01/joachim-s...,Hat sie eine Affäre? Joachim Sauer glaubt Ange...,Wo treibt sie sich immer bis spät in die Nacht...,wirtschaft,2018-01-09 00:00:00,Postillion,1,NaN
4,773237,http://www.der-postillon.com/2018/01/halb-so-s...,"""Er hat ja nur HALBneger gesagt"": So begründet...",Der Parteivorstand drückt nochmal ein Auge zu:...,wirtschaft,2018-01-08 00:00:00,Postillion,1,NaN
...,...,...,...,...,...,...,...,...,...
63863,838144,http://www.kleinezeitung.at//international/537...,Lehrer entging durch Hochzeit mit Schülerin Ve...,55-Jähriger muss nach Sex mit damals 15-Jährig...,International,2018-02-26 00:00:00,Kleine,0,NaN
63864,838145,http://www.kleinezeitung.at//wirtschaft/wirtsc...,Warum die Taiwaner Toilettenpapier bunkern,Aus Angst vor Preiserhöhungen bei Klopapier ka...,Wirtschaft,2018-02-26 00:00:00,Kleine,0,NaN
63865,838146,http://www.kleinezeitung.at//wirtschaft/wirtsc...,Warum die Taiwaner Toilettenpapier bunkern,Aus Angst vor Preiserhöhungen bei Klopapier ka...,Wirtschaft,2018-02-26 00:00:00,Kleine,0,NaN
63866,838147,http://www.kleinezeitung.at//wirtschaft/wirtsc...,\r\nDie neue Premium-Klasse von Samsung\r\n ...,Am Vorabend der Eröffnung des Mobile World Con...,Wirtschaft,2018-02-25 00:00:00,Kleine,0,NaN
63867,838148,http://www.kleinezeitung.at//kultur/klassik/53...,"Dirigent Gustav Kuhn wehrt sich gegen ""haltlos...","Gustav Kuhn, künstlerischer Leiter der Festspi...",Kultur,2018-02-26 00:00:00,Kleine,0,NaN

In [4]:
FNDatasetGerman.nunique(dropna=False)

id           63868
url          63868
Titel        61437
Body         62578
Kategorie       35
Datum         3482
Quelle           7
Fake             2
Art              6
dtype: int64

In [5]:
uniques = dict()
for colname in ["Kategorie","Quelle","Fake","Art"]:
    uniques[colname] = FNDatasetGerman[colname].unique()

In [6]:
uniques

{'Kategorie': array(['wirtschaft', 'sport', 'leute', 'medien', 'wissenschaft',
        'panorama', 'Weltnachrichten', 'Inlandsnachrichten',
        'Unternehmensnachrichten', 'Wirtschaftsnachrichten',
        'Marktnachrichten', 'Top-Nachrichten', 'Politik',
        'nlandsnachrichten', 'irtschaftsnachrichten', 'eltnachrichten',
        'nternehmensnachrichten', 'arktnachrichten', 'op-Nachrichten',
        'Wirtschaft', 'Chronik', 'International', 'Kultur', 'Wissen',
        'Gesundheit', 'Panorama', nan, 'LEBEN', 'MEDIEN', 'BUSINESS',
        'HIGHTECH', 'ADHOC', 'Österreich', 'Sport', 'Leute'], dtype=object),
 'Quelle': array(['Postillion', 'Reuters', 'Tagespresse', 'Zeitspiegel',
        'Einezeitung', 'Pressetext', 'Kleine'], dtype=object),
 'Fake': array([1, 0]),
 'Art': array([nan, 'pte', 'pts', 'pta', 'ptp', 'None'], dtype=object)}

In [7]:
grouping = FNDatasetGerman.groupby("Fake")
realNewsFNDG = grouping.get_group(0)
fakeNewsFNDG = grouping.get_group(1)

In [8]:
len(realNewsFNDG)

59241

In [9]:
suniques = dict()
for news,fake in zip([realNewsFNDG,fakeNewsFNDG],("Real","Fake")):
    for colname in ["Kategorie","Quelle","Art"]:
        suniques[(fake,colname)] = news[colname].value_counts(dropna=False)

In [10]:
pprint(suniques)

{('Fake', 'Art'): NaN    4627
Name: Art, dtype: int64,
 ('Fake', 'Kategorie'): NaN              1322
wirtschaft        938
panorama          495
Chronik           483
Politik           445
sport             308
International     152
Wirtschaft        142
wissenschaft      129
medien             85
leute              85
Wissen             14
Panorama           12
Gesundheit         10
Kultur              7
Name: Kategorie, dtype: int64,
 ('Fake', 'Quelle'): Postillion     2040
Einezeitung    1322
Tagespresse    1130
Zeitspiegel     135
Name: Quelle, dtype: int64,
 ('Real', 'Art'): NaN     36345
pte     14191
pts      7373
ptp       934
pta       392
None        6
Name: Art, dtype: int64,
 ('Real', 'Kategorie'): Weltnachrichten            9626
Unternehmensnachrichten    7968
BUSINESS                   6628
LEBEN                      6436
Inlandsnachrichten         5461
HIGHTECH                   4842
MEDIEN                     4598
Wirtschaftsnachrichten     4497
Top-Nachrichten            2884
Marktnachrichten           1669
Politik                    1391
International               579
Wirtschaft                  538
Österreich                  522
ADHOC                       392
Sport                       352
Leute                       337
Kultur                      193
eltnachrichten              128
nlandsnachrichten           116
irtschaftsnachrichten        41
nternehmensnachrichten       39
arktnachrichten               3
op-Nachrichten                1
Name: Kategorie, dtype: int64,
 ('Real', 'Quelle'): Reuters       32984
Pressetext    22896
Kleine         3361
Name: Quelle, dtype: int64}

Now for the analysis of GermanFakeNC:

In [11]:
germanFakeNC = pd.read_json(r"datasets/GermanFakeNC.json",encoding="utf-8")
germanFakeNC

,Date,URL,False_Statement_1_Location,False_Statement_1_Index,False_Statement_2_Location,False_Statement_2_Index,False_Statement_3_Location,False_Statement_3_Index,Ratio_of_Fake_Statements,Overall_Rating
0,2017-08-30,https://schluesselkindblog.com/2017/08/30/proz...,Text,213-237,,,,,1,0.7
1,2017-12-18,http://blauerbote.com/2017/12/18/bild-journali...,Text,13-36,Text,52-81,,,3,0.8
2,2017-06-02,http://blauerbote.com/2017/06/02/angela-merkel...,Title,1-7,Text,70-94,Text,121-153,3,0.7
3,2017-09-25,http://smopo.ch/deutschlands-neonazis-waehlen-...,Title,1-5,Text,28-53,Text,127-141,3,0.8
4,2018-02-17,http://www.truth24.net/gruppenvergewaltigung-s...,Title,1-1,Title,3-4,Title,6-7,1,0.4
...,...,...,...,...,...,...,...,...,...,...
485,2017-11-01,http://www.anonymousnews.ru/2017/11/01/sex-dsc...,Image,,Image,,Image,,3,0.8
486,2017-11-17,https://blog.halle-leaks.de/messer-jihad-in-ko...,Title,1-10,Image,,,,1,0.7
487,2017-10-29,https://blog.halle-leaks.de/erzieherin-will-vo...,Title,1-12,Text,1-32,Text,1-32,2,0.8
488,2017-12-30,https://www.compact-online.de/armer-martin-sch...,Text,132-142,Text,143-169,,,1,0.4
489,2018-02-24,https://de.sott.net/article/32263-Kindesmissbr...,Title,1-12,Text,50-111,Text,557-591,2,0.7

In [12]:
germanFakeNC.columns

Index(['Date', 'URL', 'False_Statement_1_Location', 'False_Statement_1_Index',
       'False_Statement_2_Location', 'False_Statement_2_Index',
       'False_Statement_3_Location', 'False_Statement_3_Index',
       'Ratio_of_Fake_Statements', 'Overall_Rating'],
      dtype='object')

In [13]:
germanFakeNC.nunique(dropna=False)

Date                          211
URL                           490
False_Statement_1_Location      4
False_Statement_1_Index       253
False_Statement_2_Location      5
False_Statement_2_Index       276
False_Statement_3_Location      5
False_Statement_3_Index       157
Ratio_of_Fake_Statements        5
Overall_Rating                 10
dtype: int64

In [14]:
gFNC_uniques = dict()
for colname in ["False_Statement_1_Location",
                "False_Statement_2_Location",
                "False_Statement_3_Location",
                "Ratio_of_Fake_Statements",
                "Overall_Rating"]:
    gFNC_uniques[colname] = germanFakeNC[colname].value_counts(dropna=False)

In [15]:
pprint(gFNC_uniques)

{'False_Statement_1_Location': Title     222
Text      198
Teaser     50
Image      20
Name: False_Statement_1_Location, dtype: int64,
 'False_Statement_2_Location': Text      248
          171
Teaser     33
Title      22
Image      16
Name: False_Statement_2_Location, dtype: int64,
 'False_Statement_3_Location':           327
Text      149
Image       6
Teaser      5
Title       3
Name: False_Statement_3_Location, dtype: int64,
 'Overall_Rating': 0.7    91
0.8    89
0.6    88
0.5    51
0.3    50
0.2    37
0.4    36
0.9    31
1.0    12
0.1     5
Name: Overall_Rating, dtype: int64,
 'Ratio_of_Fake_Statements': 1    235
2    149
3     82
4     20
9      4
Name: Ratio_of_Fake_Statements, dtype: int64}